name: "Security Scan - Bandit (Windows)"

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  bandit_scan:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan (generate JSON and HTML, always exit 0)
        run: |
          bandit -r . -f json -o bandit-report.json --exit-zero
          bandit -r . -f html -o bandit-report.html --exit-zero

      - name: Create Bandit High Severity Checker Script
        shell: pwsh
        run: |
          $script = @"
          import json
          import sys

          report_path = sys.argv[1]

          with open(report_path) as f:
              data = json.load(f)

          issues = data.get('results', [])
          high_severity = [i for i in issues if i.get('issue_severity') == 'HIGH']

          if high_severity:
              print(f'Found {len(high_severity)} HIGH severity issue(s):')
              for issue in high_severity:
                  print(f'- {issue.get('filename')}:{issue.get('line_number')} -> {issue.get('issue_text')}')
              # Do NOT exit with error to avoid failing workflow
              sys.exit(0)
          else:
              print('✅ No HIGH severity issues found.')
              sys.exit(0)
          "@
          $script | Out-File -Encoding utf8 check_bandit_high_severity.py

      - name: Check for High Severity Issues
        shell: pwsh
        continue-on-error: true
        run: python check_bandit_high_severity.py bandit-report.json

      - name: Upload Bandit Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Bandit Reports
          path: |
            bandit-report.json
            bandit-report.html
