name: "Security Scan - Bandit"

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  bandit_scan:
    name: Run Bandit Security Scanner
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -f json -o bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: Bandit JSON Report
          path: bandit-report.json

      - name: Show Bandit Report Summary
        run: |
          echo "=== Bandit Results ==="
          bandit -r . -lll
