name: "Security Scan - Bandit"

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  bandit_scan:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan (exit zero)
        run: bandit -r . -f json -o bandit-report.json --exit-zero

      - name: Check for High Severity Issues
        run: |
          python check_bandit_high_severity.py bandit-report.json

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Bandit JSON Report
          path: bandit-report.json
