name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: self-hosted  # This tells GitHub to use your self-hosted runner

    steps:
      - name: Print Hello
        run: echo "✅ Runner is working!"
