name: Selenium UI Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Selenium tests
        run: |
          python -m unittest discover -s tests/ui
